// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWoLp8XkTzQy8Dz-VjuNJGMOikxXlcFbQ',
    appId: '1:850807793037:web:0af3759a7919348ae7c9c4',
    messagingSenderId: '850807793037',
    projectId: 'daysfitnesschallenge-6c73a',
    authDomain: 'daysfitnesschallenge-6c73a.firebaseapp.com',
    storageBucket: 'daysfitnesschallenge-6c73a.firebasestorage.app',
    measurementId: 'G-8NJMTKF42G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUSMleXaJ5CDMqFON0g13ByEG3IwF_wMg',
    appId: '1:850807793037:android:42c0b320a0b2127fe7c9c4',
    messagingSenderId: '850807793037',
    projectId: 'daysfitnesschallenge-6c73a',
    storageBucket: 'daysfitnesschallenge-6c73a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZORRxyICEcmF0i8Gr79IAY2lCddxc7sE',
    appId: '1:850807793037:ios:f2c10d3f8a584ebfe7c9c4',
    messagingSenderId: '850807793037',
    projectId: 'daysfitnesschallenge-6c73a',
    storageBucket: 'daysfitnesschallenge-6c73a.firebasestorage.app',
    iosBundleId: 'com.example.healthGymProjectAltamash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZORRxyICEcmF0i8Gr79IAY2lCddxc7sE',
    appId: '1:850807793037:ios:f2c10d3f8a584ebfe7c9c4',
    messagingSenderId: '850807793037',
    projectId: 'daysfitnesschallenge-6c73a',
    storageBucket: 'daysfitnesschallenge-6c73a.firebasestorage.app',
    iosBundleId: 'com.example.healthGymProjectAltamash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWoLp8XkTzQy8Dz-VjuNJGMOikxXlcFbQ',
    appId: '1:850807793037:web:aa6f058f2bd74f6de7c9c4',
    messagingSenderId: '850807793037',
    projectId: 'daysfitnesschallenge-6c73a',
    authDomain: 'daysfitnesschallenge-6c73a.firebaseapp.com',
    storageBucket: 'daysfitnesschallenge-6c73a.firebasestorage.app',
    measurementId: 'G-QRXH1XL4GW',
  );

}